function path_inclusion = antenna_FoV(theta, phi, FoV_limits)
    path_inclusion = ((phi <= 0+FoV_limits(1)/2) ...
                       | (phi >= 360-FoV_limits(1)/2)) ...
                       & ((theta <= 90+FoV_limits(2)/2) ...
                       & (theta >= 90-FoV_limits(2)/2));
end

